# Generated by Django 4.2.4 on 2023-09-02 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('tanks', 'Танки'), ('heals', 'Хилы'), ('dd', 'ДД'), ('sellers', 'Торговцы'), ('guildmasters', 'Гильдмастера'), ('questgivers', 'Квестгиверы'), ('smiths', 'Кузнецы'), ('tanners', 'Кожевники'), ('potionmakers', 'Зельевары'), ('spellmasters', 'Мастера заклинаний')], default='tanks', max_length=16)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.announce')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
