# Generated by Django 4.2.4 on 2023-09-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_announce_author_alter_userreaction_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
