# Generated by Django 4.2.4 on 2023-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_userreaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
